
on: push
name: deploy
jobs:
    deploy:
        name: deploy to cluster
        runs-on : ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: build and push to docker
          uses: docker/build-push-action@v1
        - name: Log in to Docker Hub
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            repository:  ${{ github.backend }}
            tag_with_ref : true
            tab_with_sha : true
            tags: ${{ github.sha }}

